<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Valitron' => array($vendorDir . '/vlucas/valitron/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Slim' => array($vendorDir . '/slim/slim'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Maatwebsite\\Excel\\' => array($vendorDir . '/maatwebsite/excel/src'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
);
